trigger:
- feature/*

pool: devops-pool

variables:
  - name: dir
    value: $(System.DefaultWorkingDirectory)/environments
  - group: shared-keys

stages:
- stage: installation
  displayName: Tool Installation
  jobs:
  - job: tool
    displayName: Terraform Install
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

- stage: codevalidation
  displayName: Code Validation
  jobs:
  - job: validate
    displayName: Terrafrom Validate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(dir)/dev'
        commandOptions: '-backend=false'
        backendServiceArm: 'aks-sc'
        backendAzureRmStorageAccountName: 'strmono'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'axion-dev-statefile'
      displayName: Init
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(dir)/dev'
      displayName: Validate
  
  - job: formatting
    displayName: Terrafrom fmt
    dependsOn: validate
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'terraform fmt -check -recursive'
        workingDirectory: '$(dir)/dev'
      displayName: fmt

- stage: securityandlinting
  displayName: Security And Linting
  jobs:
  - job: linting
    displayName: Linting (tflint)
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip -OutFile tflint.zip
          Expand-Archive tflint.zip -DestinationPath tflint
          $env:Path += ";$(System.DefaultWorkingDirectory)/tflint"
        workingDirectory: '$(dir)/dev'
      displayName: Tflint Installation
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          tflint --init
          tflint --chdir .
        workingDirectory: '$(dir)/dev'
      displayName: Run Tflint
  
  - job: security
    displayName: Security Scanning(tfsec)
    dependsOn: linting
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.exe -OutFile tfsec.exe
          New-Item -ItemType Directory -Name tfsec -Force
          Move-Item tfsec.exe tfsec/tfsec.exe
          $env:Path += ";$(System.DefaultWorkingDirectory)/tfsec"
          tfsec --version
        workingDirectory: '$(dir)/dev'
      displayName: Tfsec Installation
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'tfsec .'
        workingDirectory: '$(dir)/dev'

    
- stage: plan
  displayName: Aks-Infra-planning
  jobs:
    - job: planning
      displayName: Aks-Infra-Plan
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(dir)/dev'
          backendServiceArm: 'aks-sc'
          backendAzureRmStorageAccountName: 'strmono'
          backendAzureRmContainerName: 'statefile'
          backendAzureRmKey: 'axion-dev-statefile'
        displayName: Init
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(dir)/dev'
          environmentServiceNameAzureRM: 'aks-sc'
        displayName: Plan

- stage: cost
  displayName: Cost Estimation
  jobs:
  - job: cost
    displayName: Cost Estimation
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(dir)/dev'
        backendServiceArm: 'aks-sc'
        backendAzureRmStorageAccountName: 'strmono'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'axion-dev-statefile'
      displayName: Init
    - task: InfracostSetup@2
      inputs:
        apiKey: '$(infracost-api-key)'
        version: '0.10.x'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'infracost breakdown --path $(dir)/dev'

- stage: manualapproval
  displayName: Manual Validation
  pool: server
  jobs:
    - job: approval
      displayName: Manual Approval
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'vikasshri2308@gmail.com'
        
